# PANDAS

In [3]:
import pandas as pd
import numpy as np

## SERIES

### BASIC DEFINITIONS

* IT IS A PANDAS DATA STRUCTURE 
* IT IS UNIDIRECTIONAL 
* HAVE TWO TYPES OF INDICES 
    * DEFAULT 
    * LABELLED
* IT IS HOMOGENEOUS DATA STRUCTURE

#### IDENTIFICARION OF SERIES

* index 1-----value 1 
* index 2-----value 2
* index 3-----value 3
* index 4-----value 4
* dtype: Datatype of values

### SYNTAX TO DEFINE A SERIES

* Identifier=pd.series(data structure,index=list of index)

In [4]:
a=pd.Series() #EMPTY SERIES 
a

Series([], dtype: object)

In [5]:
a=pd.Series([1,2,3,4,5]) #with default index 
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e']) # with labelled index
a

a    1
b    2
c    3
d    4
e    5
dtype: int64

#### Dictionary to series

In [7]:
marks={"Alice": 85, "Bob": 90, "Charlie": 78} #dictionary
a=pd.Series(marks) #creating series from dictionary
a

Alice      85
Bob        90
Charlie    78
dtype: int64

* IF WE WANT SERIES WITH CUSTOM INDEX WE CAN GIVE IT AND IT WILL ACCESS INDEX
* PRIORITY IS GIVEN TO INDEX 
* IF THE ELEMENT IN INDEX LIST IS NOT FOUND THEN RETURN NAN

In [8]:
a=pd.Series(marks,index=['Bob','Alice']) 
a

Bob      90
Alice    85
dtype: int64

In [9]:
a=pd.Series(marks,index=['Bob','Alice','David']) #David is not in the dictionary so it will be NaN
a

Bob      90.0
Alice    85.0
David     NaN
dtype: float64

### SERIES ATTRIBUTES

In [10]:
sales=pd.Series({'mango':1000,'banana':500,'apple':800})
sales

mango     1000
banana     500
apple      800
dtype: int64

In [11]:
sales.values #to get the values of the series

array([1000,  500,  800])

In [12]:
sales.index

Index(['mango', 'banana', 'apple'], dtype='str')

In [13]:
sales.name

In [14]:
sales.ndim

1

In [15]:
sales.shape

(3,)

In [16]:
sales.size

3

In [17]:
sales.itemsize #ERROR

AttributeError: 'Series' object has no attribute 'itemsize'

In [ ]:
sales.nbytes #3 elements * 8 bytes each = 24 bytes

24

In [ ]:
itemsize=sales.nbytes/sales.size
itemsize

8.0

In [ ]:
sales.empty

False

In [ ]:
sales.hasnans #to check if there are any NaN values in the series

False

In [ ]:
s=pd.Series(["sushant",np.nan]) #it has a nan value so it will return True
s.hasnans

True

### ACCESSING SERIES

In [ ]:
#Default index
even = pd.Series([2, 4, 6, 8, 10])
even

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
#Labelled index
sales=pd.Series({'mango':1000,'banana':500,'apple':800}) 
sales

mango     1000
banana     500
apple      800
dtype: int64

In [ ]:
tens=pd.Series([100,200,300,400,500],dtype="float64",index=[1,2,3,4,5])
tens

1    100.0
2    200.0
3    300.0
4    400.0
5    500.0
dtype: float64

#### Method 1 : Seriesname[index]

yahan ye mindset leke chalna hai ki labelled index ka use karo agr labelled nhi hai then default index 
But in case of numeric it always take default in case of silicing

In [ ]:
even[0]

np.int64(2)

In [ ]:
even[-1] #error

KeyError: -1

In [ ]:
sales['mango'] #accessing value by label

np.int64(1000)

 Accessing multiple Elements

* Seriename[[index1, index2, index3....]]

In [ ]:
even[[0,1,2]] #accessing multiple values by index

0    2
1    4
2    6
dtype: int64

In [ ]:
even[[0,0,0]] #accessing same value multiple times

0    2
0    2
0    2
dtype: int64

* Slicing

In [ ]:
even[0:3] #accessing values by index range

0    2
1    4
2    6
dtype: int64

Laballed ke case mai stop nhi end hota hai

In [ ]:
sales['mango':'apple']

mango     1000
banana     500
apple      800
dtype: int64

In [ ]:
tens[2:3] #dhokhaaaaaaaaaaaaaaaa
#In numeric it doesnt take labelled index it takes default index

3    300.0
dtype: float64

#### Method 2 : iloc()

------> iloc is a function known as integer location. It is used to access elements of series on the basis of integer indexing , no matter wht type of index series have

Syntax 
* seriesname.iloc[index]

In [ ]:
even

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
tens

NameError: name 'tens' is not defined

In [ ]:
tens.iloc[3] # works on default indexing

np.float64(400.0)

In [ ]:
tens.iloc[-1]

np.float64(500.0)

In [ ]:
sales.iloc[-1]

np.int64(800)

In [ ]:
even.iloc[[0,1,2]]

0    2
1    4
2    6
dtype: int64

In [ ]:
even.iloc[[-3,-2,-1]]

2     6
3     8
4    10
dtype: int64

In [ ]:
even.iloc[1:3]

1    4
2    6
dtype: int64

#### Method 2 : loc()

--------> loc( ) is used to accesss labelled based indexing

* syntax = seriesname.loc(labelled index)

In [ ]:
even #here 0,1,2,3,4 are default and labelled index

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
even.loc[0]

np.int64(2)

In [ ]:
even.loc[-1]

KeyError: -1

In [ ]:
tens.loc[1]

np.float64(100.0)

In [ ]:
tens.loc[0] # ERROR as 0 is not the labelled index

KeyError: 0

In [ ]:
tens.loc[1:3]

1    100.0
2    200.0
3    300.0
dtype: float64

In [ ]:
sales.loc['apple']

np.int64(800)

In [ ]:
sales.loc['mango']

np.int64(1000)

### ARTHMETIC OPERATIONS

In [ ]:
s=pd.Series([2,np.nan,6,7,8])
s

0    2.0
1    NaN
2    6.0
3    7.0
4    8.0
dtype: float64

#### ADDITION

--------------------> SINGLE VALUE

In [ ]:
s+10 #10 will get added to all the characters in the series

0    12.0
1     NaN
2    16.0
3    17.0
4    18.0
dtype: float64

* add( )

In [ ]:
s.add(10)

0    12.0
1     NaN
2    16.0
3    17.0
4    18.0
dtype: float64

In [ ]:
s.add(10,fill_value=0) #It will fill the value of nan to 0

0    12.0
1    10.0
2    16.0
3    17.0
4    18.0
dtype: float64

--------------------> WITH ANOTHER SERIES

In [ ]:
term1=pd.Series(np.random.randint(1,101,size=5))
term2=pd.Series(np.random.randint(1,101,size=5))

In [ ]:
term1+term2 #WHEN SIZE SAME THEN CORRESPONDING ELEMENTS ADD WITH EACHOTHER

0     13
1     95
2     84
3     63
4    160
dtype: int32

In [ ]:
term1=pd.Series(np.random.randint(1,101,size=4))

In [ ]:
term1+term2 # WITH DIFF SIZE THEN IT WILL ASSUME THAT THE LAST VALUE WHICH IS 4th INDEX OF TERM! IS NAN

0    30.0
1    29.0
2    31.0
3    62.0
4     NaN
dtype: float64

In [ ]:
term2.add(term1,fill_value=0) #WILL MAKE THE 4TH INDEX OF TERM1 TO BE 0

0    30.0
1    29.0
2    31.0
3    62.0
4    70.0
dtype: float64

------------------------> ADDITION WITH SOME DIFF INDEX AND SOME DIFF INDEX

In [ ]:
term1=pd.Series(np.random.randint(1,101,size=6),index=['sushant','rishu','himanshu','priya','ravi','messi'])
term2=pd.Series(np.random.randint(1,101,size=6),index=['sushant','rishu','ronaldo','pedri','priya','rodri'])

In [ ]:
term1+term2 #IT WILL ADD ACC TO INDEX AND WILL TAKE NAN IF IT IS NOT IN ONE SERIES

himanshu      NaN
messi         NaN
pedri         NaN
priya        80.0
ravi          NaN
rishu       120.0
rodri         NaN
ronaldo       NaN
sushant     131.0
dtype: float64

In [ ]:
term1.add(term2,fill_value=0) #IT WILL FILL THE NAN VALUE WITH 0

himanshu     43.0
messi        13.0
pedri        87.0
priya        80.0
ravi         64.0
rishu       120.0
rodri         8.0
ronaldo      82.0
sushant     131.0
dtype: float64

#### SUBTRACTION

### COMPARISON OPERATIONS

In [ ]:
s=pd.Series(np.random.randint(1,101,size=5))
p=pd.Series(np.random.randint(1,101,size=5))
s

0    88
1    31
2    64
3    33
4    65
dtype: int32

In [ ]:
p

0    93
1    93
2     5
3    37
4    69
dtype: int32

In [ ]:
s>75 #GIVES TRUE WHERE ELEMENT SATISFIES THE CONDITION

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
s<p

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [ ]:
20>np.nan #NAN IS NEITHER GREATER THAN ANYTHING NOR SMALLLER THAN ANYTHING IT WILL ALWAYS GIVE NAN

False

In [ ]:
term1=pd.Series(np.random.randint(1,101,size=6),index=['sushant','rishu','himanshu','priya','ravi','messi'])
term2=pd.Series(np.random.randint(1,101,size=6),index=['sushant','rishu','ronaldo','pedri','priya','rodri'])

In [ ]:
term1>term2 #COMPARISON OPERATOR ONLY COMPARE WHEN LABELLED INDEX ARE SAME
#SAME HAPPENS WHEN SiZE IS DIFF

ValueError: Can only compare identically-labeled Series objects

### DATA FILTERATION

In [ ]:
marks=pd.Series(np.random.randint(1,101,size=5))
marks

0    59
1    31
2    47
3    39
4    21
dtype: int32

------------> BOOLEAN INDEXING

* IF WE WANT FIRST 3 ELEMENTS

In [ ]:
marks[[True,True,True,False,False]]

0    59
1    31
2    47
dtype: int32

* IF WE WANT ELEMENTS IN WHICH DATA IS GREATER THAN 50

In [ ]:
marks[marks>50]

0    59
dtype: int32

### TEXT HANDLING

IT IS PROCESS TO HANDLE OR MANAGE THE TEXT OR STRING DATA IN A SERIES

In [ ]:
name=["raVi vohra","riSHu DIPke","susHANt CHOUdhary","Dhurandar RAina"]
s=pd.Series(name)
s

0           raVi vohra
1          riSHu DIPke
2    susHANt CHOUdhary
3      Dhurandar RAina
dtype: str

* TO HANDLE THE TEXT WE HAVE MULTIPLE METHODS RELATED TO THE TEXT OR STRING SUCH AS UPPER( ) , LOWER( ) , ISUPPER( ) ETC

In [ ]:
s.upper() #ERROR ------> WE CAN'T IMPLEMENT THESE METHODS DIRECTLY TO THE SERIES

AttributeError: 'Series' object has no attribute 'upper'

--------> SO TO APPLY STRINGS METHOD , WE HAVE TO USE STR SUBMODULE WITH SERIES

* syntax 
* seriesName.str.string_Method

In [ ]:
s.str.upper()

0         RAVI
1        RISHU
2      SUSHANT
3    DHURANDAR
dtype: str

In [ ]:
s.str.title() #IT will make the text in title case means every word first word capital

0           Ravi Vohra
1          Rishu Dipke
2    Sushant Choudhary
3      Dhurandar Raina
dtype: str

In [ ]:
s.str.capitalize()

0           Ravi vohra
1          Rishu dipke
2    Sushant choudhary
3      Dhurandar raina
dtype: str

In [ ]:
words=s.str.split() # IT WILL SPLIT THE WORDS IN THE SERIES AND GIVE SERIES OF LIST OF STRING
words

0           [raVi, vohra]
1          [riSHu, DIPke]
2    [susHANt, CHOUdhary]
3      [Dhurandar, RAina]
dtype: object

In [ ]:
s.str.replace(" ","@") #IT REPLACE ALL THE SPACE WITH @

0           raVi@vohra
1          riSHu@DIPke
2    susHANt@CHOUdhary
3      Dhurandar@RAina
dtype: str

In [ ]:
words.str.join("@") #IT JOINS SERIES OF LIST OF STRINGS WITH THE PARAMETER GIVING INSIDE

0           raVi@vohra
1          riSHu@DIPke
2    susHANt@CHOUdhary
3      Dhurandar@RAina
dtype: object

In [ ]:
s.str.join(" ") #JOIN FUNCTION WHEN USED IN STRING TAKES INDIVIDUAL ELEMENTS FROM A STRING AND GIVES A GAP BTW THEM

0                  r a V i   v o h r a
1                r i S H u   D I P k e
2    s u s H A N t   C H O U d h a r y
3        D h u r a n d a r   R A i n a
dtype: str

In [ ]:
a=["####sushant====","!!!ri***","+++lalala----"]
z=pd.Series(a)
z

0    ####sushant====
1           !!!ri***
2      +++lalala----
dtype: str

WE HAVE TO CLEAN THE UPPER GIVEN DATA

In [ ]:
z.str.strip("#*-+=!")

0    sushant
1         ri
2     lalala
dtype: str

QUESTION - CLEAN THIS RANDOM DATA GIVEN

In [ ]:
text = pd.Series([
    "   Python@@@Programming   ",
    "\tData###Science\t",
    "**Machine   Learning**",
    "   Artificial@@@Intelligence###   ",
    "Deep---Learning!!!",
    "\nSQL___Basics\n",
    "  Pandas@@@Library###  ",
    "\tNumPy%%%Arrays\t",
    "Matplotlib***Charts!!!",
    "Data$$$Visualization###",
    "Hello@@@###World!!!",
    "Clean___This---Text",
    "**Welcome@@@to###Python**",
    "   Learn%%%Data$$$Science   ",
    "\nAI&&&ML@@@Course###\n"
])

In [ ]:
text.str.strip("@ \t*-_!#\n").str.replace("@"," ").str.replace("#"," ").str.replace("-"," ").str.replace("_"," ").str.replace("$"," ").str.replace("&"," ").str.replace("%"," ").str.replace("*"," ").str.replace(" "," ").str.split().str.join(" ")

0          Python Programming
1                Data Science
2            Machine Learning
3     Artificial Intelligence
4               Deep Learning
5                  SQL Basics
6              Pandas Library
7                NumPy Arrays
8           Matplotlib Charts
9          Data Visualization
10                Hello World
11            Clean This Text
12          Welcome to Python
13         Learn Data Science
14               AI ML Course
dtype: object

### GETTER AND SETTER

### SAMPLING

In [ ]:
age=pd.Series(np.random.randint(18,100,size=150))
age

0      86
1      72
2      84
3      72
4      35
       ..
145    45
146    62
147    76
148    60
149    85
Length: 150, dtype: int32

In [ ]:
age.head(10) #IT RETURNS TOP N ROWS OF A SERIES (IF NOTHING IS GIVEN IN THE PARENTHESIS IT HAS BY DEFAULT 5)

0    86
1    72
2    84
3    72
4    35
5    73
6    72
7    50
8    53
9    20
dtype: int32

In [ ]:
age.head(-5) #IT WILL GIVE -5 SE PHELE KE SAARE ROWS

0      86
1      72
2      84
3      72
4      35
       ..
140    82
141    51
142    93
143    45
144    99
Length: 145, dtype: int32

In [ ]:
age.tail(10) # IT WILL GIVE LAST N ELEMENTS AND BY DEFAULT 5

140    82
141    51
142    93
143    45
144    99
145    45
146    62
147    76
148    60
149    85
dtype: int32

In [ ]:
age.tail(-5) #START KE 5 CHDKE

5      73
6      72
7      50
8      53
9      20
       ..
145    45
146    62
147    76
148    60
149    85
Length: 145, dtype: int32

#### sample( )
* IT RETURNS N NUMBER OF RANDOM ROWS FROM A DATA SET 
* BY DEFAULT IT RETURN SINGLE RANDOM ROW

In [ ]:
age.sample()

24    78
dtype: int32

In [ ]:
age.sample(5,axis=0)

127    29
89     94
132    35
118    75
125    61
dtype: int32

#### EXTRA  TIPS : Nth BASED SAMPLING

-----------> IT MEANS STEP LEKE PRINT KARVANA LIKE 5 KA STEP LEKE PRINT KRNA ELEMENT

In [ ]:
age.iloc[5::5]

5      73
10     80
15     77
20     62
25     79
30     61
35     30
40     35
45     75
50     73
55     31
60     47
65     99
70     50
75     62
80     32
85     32
90     81
95     67
100    31
105    86
110    94
115    37
120    38
125    61
130    54
135    97
140    82
145    45
dtype: int32

### NULL HANDLING

* NULL OR EMPTY DATA

In [ ]:
np.nan

nan

In [ ]:
pd.Series(np.nan)

0   NaN
dtype: float64

In [ ]:
s=pd.Series([20,30,np.nan,np.nan,50,np.nan,70])
s

0    20.0
1    30.0
2     NaN
3     NaN
4    50.0
5     NaN
6    70.0
dtype: float64

#### isna( )

In [ ]:
s.isna()

0    False
1    False
2     True
3     True
4    False
5     True
6    False
dtype: bool

#### notna( )

In [ ]:
s.notna()

0     True
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [ ]:
s[s.notna()]

0    20.0
1    30.0
4    50.0
6    70.0
dtype: float64

#### hasnans

In [ ]:
s.hasnans

True

dropna( )

In [ ]:
s.dropna()

0    20.0
1    30.0
4    50.0
6    70.0
dtype: float64

In [ ]:
a=s
a

0    20.0
1    30.0
2     NaN
3     NaN
4    50.0
5     NaN
6    70.0
dtype: float64

In [ ]:
a.dropna(inplace=True) #inplace = true creates a permanent change in the series by default inplace is equal to false which means it will do temporary change 
a

0    20.0
1    30.0
4    50.0
6    70.0
dtype: float64

In [ ]:
a.dropna(ignore_index=True) #It will ignore existing index

0    20.0
1    30.0
2    50.0
3    70.0
dtype: float64

In [ ]:
z=s

In [ ]:
z.dropna(ignore_index=True , inplace= True)
z

0    20.0
1    30.0
2    50.0
3    70.0
dtype: float64

#### fillna( )

In [ ]:
s.fillna(0)

0    20.0
1    30.0
2     0.0
3     0.0
4    50.0
5     0.0
6    70.0
dtype: float64

In [ ]:
c=s

In [ ]:
c.fillna(0,inplace=True)

0    20.0
1    30.0
2     0.0
3     0.0
4    50.0
5     0.0
6    70.0
dtype: float64

In [ ]:
c

0    20.0
1    30.0
2     0.0
3     0.0
4    50.0
5     0.0
6    70.0
dtype: float64

### AGGERATION AND STATISTICAL MEASURES

In [ ]:
salary=pd.Series(np.random.randint(10000,150001,size=10))
salary

0     99979
1     13355
2     37101
3     78301
4     79357
5     12768
6    127177
7    123086
8     86615
9    138396
dtype: int32

In [ ]:
np.sum(salary) #in numpy

np.int64(796135)

In [ ]:
salary.sum() #in pandas

np.int64(796135)

In [ ]:
sum(salary) #in normal python

796135

In [ ]:
max(salary)

138396

In [ ]:
np.max(salary)

np.int32(138396)

In [ ]:
salary.max()

np.int32(138396)

In [ ]:
salary.count()

np.int64(10)

In [ ]:
salary.size

10

In [ ]:
len(salary)

10

In [ ]:
np.mean(salary) #GIVES AVG

np.float64(79613.5)

In [ ]:
salary.mean()

np.float64(79613.5)

In [ ]:
np.median(salary)

np.float64(82986.0)

In [ ]:
salary.median()

np.float64(82986.0)

In [ ]:
salar=pd.Series([1000,2000,1000,2000,10000])
salar

0     1000
1     2000
2     1000
3     2000
4    10000
dtype: int64

In [ ]:
salar.mode()

0    1000
1    2000
dtype: int64

In [ ]:
salary.std()

np.float64(45630.049169014346)

In [ ]:
salary.describe() # THIS IS IMPPPPPPPPPPPP , REMEMBER THIS ONLY

count        10.000000
mean      79613.500000
std       45630.049169
min       12768.000000
25%       47401.000000
50%       82986.000000
75%      117309.250000
max      138396.000000
dtype: float64

### WHEN TO USE fillna( ) amd dropna( )

#### NEVER USE DROPNA WE SHOULD USE DROPNA VERY RARE 
#### BECAUSE IT WILL REMOVE ALL THE ROWS WITH DIFF DATA 
#### INSTEAD OF THIS FOR STATS CAL U CAN CALL IT DIRECTLY AS THEY IGNORE NULL AND DOESNOT COUNT IT ALSO

## DATAFRAME

### CREATION OF DATAFRAME

#### 1.USING LIST OF LIST

In [ ]:
data=[[1,2,3,4],[2,4,6,8]]
pd.DataFrame(data) #CREATING DATAFRAME FROM LIST OF LISTS

NameError: name 'pd' is not defined

In [ ]:
pd.DataFrame(data,index=['R1','R2'],columns=['C1','C2','C3','C4']) #CREATING DATAFRAME FROM LIST OF LISTS WITH LABELLED INDEX AND COLUMNS

    C1  C2  C3  C4
R1   1   2   3   4
R2   2   4   6   8

In [ ]:
df=pd.DataFrame(data,index=['R1','R2'],columns=['C1','C2','C3','C4'])
df

    C1  C2  C3  C4
R1   1   2   3   4
R2   2   4   6   8

------------------> if size of nested list is not same then Nan gets in the place

In [ ]:
f=[[1,2,3,4],[2,4,6,8,10]]
pd.DataFrame(f) #NaN gets in the empty place of the missing value in the dataframe

   0  1  2  3     4
0  1  2  3  4   NaN
1  2  4  6  8  10.0

In [ ]:
d=[[101,'Aarav', 'HR', 45000],[102,'Siya', 'IT', 65000],[103,'Kabir', 'Sales', 52000],[104,'Meera', 'Finance', 70000],]
pd.DataFrame(d,columns=['ID','Name','Department','Salary']) #CREATING DATAFRAME FROM LIST OF LISTS WITH LABELLED COLUMNS

    ID   Name Department  Salary
0  101  Aarav         HR   45000
1  102   Siya         IT   65000
2  103  Kabir      Sales   52000
3  104  Meera    Finance   70000

#### 2. List of Dictionary

In [ ]:
data=[{'a': 1, 'b': 2,'c': 3}, {'a': 3, 'b': 4, 'c': 5}]
pd.DataFrame(data) #CREATING DATAFRAME FROM LIST OF DICTIONARIES

   a  b  c
0  1  2  3
1  3  4  5

In [ ]:
pd.DataFrame(data,columns=['a','b','c','d']) #CREATING DATAFRAME FROM LIST OF LISTS WITH COLUMN NAMES

   a  b  c   d
0  1  2  3 NaN
1  3  4  5 NaN

-----------> PRIORITY IS GIVEN TO COLUMNS WRITTEN OUTSIDE NOT THE ONE IN THE DICTIONARY THAT'S WHY IT HAS ALSO TAKEN d AND ASSIGNED NaN THERE

#### Using DICTIONARY OF LISTS

In [ ]:
a={"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35], "city": ["New York", "Los Angeles", "Chicago"]}
pd.DataFrame(a,index=['R1','R2','R3']) #CREATING DATAFRAME FROM DICTIONARY OF LISTS

       name  age         city
R1    Alice   25     New York
R2      Bob   30  Los Angeles
R3  Charlie   35      Chicago

In [ ]:
d={"Emp_ID": [101, 102, 103], "Emp_Name": ["Aarav", "Siya", "Kabir"], "Emp_Department": ["HR", "IT", "Sales"], "Emp_Salary": [45000, 65000, 52000]}
pd.DataFrame(d) #CREATING DATAFRAME FROM DICTIONARY OF LISTS

   Emp_ID Emp_Name Emp_Department  Emp_Salary
0     101    Aarav             HR       45000
1     102     Siya             IT       65000
2     103    Kabir          Sales       52000

### ATTRIBUTES OF DATAFRAME

In [ ]:
a={"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35], "city": ["New York", "Los Angeles", "Chicago"]}
df=pd.DataFrame(a,index=['R1','R2','R3']) #CREATING DATAFRAME FROM DICTIONARY OF LISTS
df

       name  age         city
R1    Alice   25     New York
R2      Bob   30  Los Angeles
R3  Charlie   35      Chicago

In [ ]:
df.ndim

2

In [ ]:
df.shape

(3, 3)

In [ ]:
df.index

Index(['R1', 'R2', 'R3'], dtype='str')

In [ ]:
df.index=['a','b','c'] #changing the index of the dataframe
df

      name  age         city
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago

In [ ]:
df.columns #SAME CAN BE DONE FOR COLUMNS ALSO BY WRITING df.columns=['C1','C2','C3']

Index(['name', 'age', 'city'], dtype='str')

-------------------> CONVERT ALL THE COLUMNS NAME INTO UPPER CASE

In [ ]:
df.columns=df.columns.str.upper() #changing the column names to upper case
df

      NAME  AGE         CITY
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago

--------------> COUNT NUMBER OF ROWS

In [ ]:
df.shape[0] #gives the number of rows in the dataframe # METHOD 1

3

In [ ]:
len(df.index)  #METHOD 2

3

### ACCESSING DATAFRAME

In [60]:
df = pd.DataFrame({"Emp_id":[101,102,103,104],
                 "Name":["Himanshu","rishu","sushant","ravi"],
                 "Department":["Hr","servent","salesman","marketing",],
                 "Salary":[10000,12000,15000,13000]})
df

   Emp_id      Name Department  Salary
0     101  Himanshu         Hr   10000
1     102     rishu    servent   12000
2     103   sushant   salesman   15000
3     104      ravi  marketing   13000

#### USING SUBSCRIPT
------------> dataframe_name[column name] and for multi column dataframe_name[[column name1,column name2,column name n]]

In [ ]:
df['age'] #accessing a single column

R1    25
R2    30
R3    35
Name: age, dtype: int64

In [ ]:
df[['name','age']] #accessing multiple columns in the dataframe

       name  age
R1    Alice   25
R2      Bob   30
R3  Charlie   35

#### CHANGING COLUMN OF DATAFRAME

In [ ]:
df=df[['name','city','age']] #rearranging the columns in the dataframe
df

       name         city  age
R1    Alice     New York   25
R2      Bob  Los Angeles   30
R3  Charlie      Chicago   35

In [ ]:
df.columns=['a','b','c'] #changing the column names of the dataframe
df

          a            b   c
R1    Alice     New York  25
R2      Bob  Los Angeles  30
R3  Charlie      Chicago  35

In [ ]:
df.columns=df.columns.str.upper() #changing the column names to upper case
df

       NAME         CITY  AGE
R1    Alice     New York   25
R2      Bob  Los Angeles   30
R3  Charlie      Chicago   35

----------------> CREATING A NEW COLUMN

In [63]:
df['d']=10 #adding a new column to the dataframe with default value 10
df

   Emp_id      Name Department  Salary   d
0     101  Himanshu         Hr   10000  10
1     102     rishu    servent   12000  10
2     103   sushant   salesman   15000  10
3     104      ravi  marketing   13000  10

#### USING SLICING

In [ ]:
df[::]

       name  age         city
R1    Alice   25     New York
R2      Bob   30  Los Angeles
R3  Charlie   35      Chicago

#### LOC( )

df.loc(rowIndex,cloumn)
*       single   single 
*       multiple multiple
*       slicing  slicing

In [ ]:
df.loc['R1'] #accessing the first row

name       Alice
city    New York
age           25
Name: R1, dtype: object

In [ ]:
df.loc['R1', 'name']

'Alice'

In [ ]:
df.loc[['R1','R2'], ['name', 'age']] #accessing multiple rows and columns

     name  age
R1  Alice   25
R2    Bob   30

In [ ]:
df.loc['R1':, ['name', 'age']] #accessing specific rows and columns

       name  age
R1    Alice   25
R2      Bob   30
R3  Charlie   35

In [ ]:
df.loc['R1', ['name', 'age']] #accessing specific row and columns

name    Alice
age        25
Name: R1, dtype: object

#### ILOC( )

In [ ]:
df.iloc[0] #accessing the first row using integer location

name       Alice
city    New York
age           25
Name: R1, dtype: object

In [ ]:
df.iloc[:,1] #accessing the second column using integer location

R1       New York
R2    Los Angeles
R3        Chicago
Name: city, dtype: str

In [ ]:
df.iloc[:,[1,2]]

           city  age
R1     New York   25
R2  Los Angeles   30
R3      Chicago   35

In [ ]:
df.iloc[0:,0:3]

       name         city  age
R1    Alice     New York   25
R2      Bob  Los Angeles   30
R3  Charlie      Chicago   35

In [ ]:
df.iloc[0:3,[0,2]]

       NAME  AGE
R1    Alice   25
R2      Bob   30
R3  Charlie   35

#### RESHUFFLING THE COLUMNS

In [ ]:
df=df[['AGE','NAME','CITY']] #rearranging the columns in the dataframe
df

KeyError: "None of [Index(['AGE', 'NAME', 'CITY'], dtype='str')] are in the [columns]"

In [ ]:
df.iloc[[0,1]]
df

      name  age         city
0    Alice   25     New York
2  Charlie   35      Chicago
1      Bob   30  Los Angeles

In [ ]:
pd.concat([df.iloc[0:1], df.iloc[1:3]])

      name  age         city
0    Alice   25     New York
2  Charlie   35      Chicago
1      Bob   30  Los Angeles

#### BOOLEAN INDEXING

In [ ]:
df[[True,True,True,True]] #accessing all rows in the dataframe

   Emp_id      Name Department  Salary
0     101  Himanshu         Hr   10000
1     102     rishu    servent   12000
2     103   sushant   salesman   15000
3     104      ravi  marketing   13000

#### COMPARISON OPERATIONS

In [ ]:
df[df['Emp_id']>30] #accessing rows based on a condition

   Emp_id      Name Department  Salary
0     101  Himanshu         Hr   10000
1     102     rishu    servent   12000
2     103   sushant   salesman   15000
3     104      ravi  marketing   13000

* How to apply multiple statements in pandas Here we can not use normal AND operator

In [ ]:
df['Department'].str.lower()=='salesman' and df['Salary']>12000

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
(df['Department'].str.lower()=='salesman') & (df['Salary']>12000)

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
df[(df['Department'].str.lower()=='salesman') & (df['Salary']>12000) ]

   Emp_id     Name Department  Salary
2     103  sushant   salesman   15000

* LOGICAL OPERATIONS WITH BOOLEAN SERIES / BOOLEAN ARRRAY
* bitwise and -----> &
* bitwise or ------> |
* bitwise not -----> ~

In [20]:
df=pd.DataFrame({"emp_id":[101,102,103,104,105,106],
                 "name":["Himanshu raina","rishu raj","SuShant Choudhary","Ravi VOHRA","ANUSHKA VATS","priya rathore"],
                 "designation":["Manager","Team LEAD","Developer","MANAGER","Data analyst","data analyst"],
                 "salary":[10000,12000,15000,13000,12000,18000]})
df

   emp_id               name   designation  salary
0     101     Himanshu raina       Manager   10000
1     102          rishu raj     Team LEAD   12000
2     103  SuShant Choudhary     Developer   15000
3     104         Ravi VOHRA       MANAGER   13000
4     105       ANUSHKA VATS  Data analyst   12000
5     106      priya rathore  data analyst   18000

TASK 1 : FIND NAME OF EMPLOYEE WHOSE SALARY IS GREATER THAN 13000

In [19]:
df[df['salary']>13000]['name'] #accessing rows based on a condition

2    SuShant Choudhary
5        priya rathore
Name: name, dtype: str

#### STRING HANDLING

In [58]:
df=pd.DataFrame({"emp_id":[101,102,103,104,105,106],
                 "name":["Himanshu raina","rishu raj","SuShant Choudhary","Ravi VOHRA","ANUSHKA VATS","priya rathore"],
                 "designation":["Manager","Team LEAD","Developer","MANAGER","Data analyst","data analyst"],
                 "salary":[10000,12000,15000,13000,12000,18000]})
df

   emp_id               name   designation  salary
0     101     Himanshu raina       Manager   10000
1     102          rishu raj     Team LEAD   12000
2     103  SuShant Choudhary     Developer   15000
3     104         Ravi VOHRA       MANAGER   13000
4     105       ANUSHKA VATS  Data analyst   12000
5     106      priya rathore  data analyst   18000

In [28]:
df['name'].str.upper() #changing the name column to upper case

0       HIMANSHU RAINA
1            RISHU RAJ
2    SUSHANT CHOUDHARY
3           RAVI VOHRA
4         ANUSHKA VATS
5        PRIYA RATHORE
Name: name, dtype: str

In [30]:
df['name'].str.upper() #changing the name column to upper case

0       HIMANSHU RAINA
1            RISHU RAJ
2    SUSHANT CHOUDHARY
3           RAVI VOHRA
4         ANUSHKA VATS
5        PRIYA RATHORE
Name: name, dtype: str

In [31]:
df['name'].str.capitalize() #changing the name column to capitalize case

0       Himanshu raina
1            Rishu raj
2    Sushant choudhary
3           Ravi vohra
4         Anushka vats
5        Priya rathore
Name: name, dtype: str

In [32]:
df['name'].str.title() #changing the name column to title case

0       Himanshu Raina
1            Rishu Raj
2    Sushant Choudhary
3           Ravi Vohra
4         Anushka Vats
5        Priya Rathore
Name: name, dtype: str

TASK : PRINT THE NAMES IN TITLE FORM OF THOSE EMPLOYEE WHOSE SALARY IS SMALLER THAN 13000

In [40]:
df[df['salary']<13000]['name'].str.title() #changing the name column to title case for those whose salary is less than 13000

0    Himanshu Raina
1         Rishu Raj
4      Anushka Vats
Name: name, dtype: str

TASK : PRINT THE NAMES IN TITLE FORM WHERE DESIGNATION IS MANAGER

In [41]:
df[df['designation'].str.lower()=='manager']['name'].str.title() #changing the name column to title case for those whose designation is manager

0    Himanshu Raina
3        Ravi Vohra
Name: name, dtype: str

In [54]:
df['name'] = df['name'].str.title() #changing the name column to title case for all the names in the dataframe
df

   emp_id               name   designation  salary
0     101     Himanshu Raina       Manager   10000
1     102          Rishu Raj     Team LEAD   12000
2     103  Sushant Choudhary     Developer   15000
3     104         Ravi Vohra       MANAGER   13000
4     105       Anushka Vats  Data analyst   12000
5     106      Priya Rathore  data analyst   18000

In [57]:
df['salary']=df['salary'].add(1000,fill_value=0) #adding 1000 to the salary column of the dataframe 
df

   emp_id               name   designation  salary
0     101     Himanshu Raina       Manager   12000
1     102          Rishu Raj     Team LEAD   14000
2     103  Sushant Choudhary     Developer   17000
3     104         Ravi Vohra       MANAGER   15000
4     105       Anushka Vats  Data analyst   14000
5     106      Priya Rathore  data analyst   20000

TASK : CLEAN THIS DATA

1. Remove leading/trailing spaces from Name, City, Product and Status.
2. Convert all names into Proper Case.
3. Convert emails into lowercase.
4. Remove spaces from email IDs.
5. Standardize phone numbers into 10-digit Indian mobile numbers.
6. Remove ₹, Rs., commas and /- from Price.
7. Convert Price from string to numeric.
8. Convert all dates into a single format: DD-MM-YYYY.
9. Standardize all Status values into Delivered, Pending, Cancelled, Returned.
10. Standardize categories such as:
11. Laptop, Laptops, LAPTOPS → Laptop
12. Mobile-Phones, Mobile Phones, mobile phones → Mobile
13. Audio, Audio-Devices → Audio
14. Extract Pincode from Address.
15. Extract State from Address wherever available.
16. Remove unnecessary punctuation from Feedback.
17. Convert Feedback into lowercase for analysis.
18. Find customers whose feedback contains words like good, excellent, amazing, or superb.
19. Filter customers where Price > ₹50,000.
20. Filter customers from Delhi/NCR.
21. Filter customers whose Status is Delivered and Price > ₹50,000.
22. Find customers whose email is from Gmail.
23. Find customers whose feedback contains ! more than once.

In [59]:
import pandas as pd

data = {
    "Customer_ID": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010",
        "C011", "C012", "C013", "C014", "C015",
        "C016", "C017", "C018", "C019", "C020"
    ],

    "Name": [
        "  Rahul Sharma ", "priya  mehta", " AMAN KHAN",
        "Neha Kapoor ", "arjun singh", "  Simran Kaur",
        "rohit.verma", " PRIYANKA JAIN ", "Karan Malhotra",
        " Meena Gupta", "Vikas  Yadav", "Sneha Patel",
        " RAJAT GUPTA ", "Anjali Singh", "mohit sharma ",
        "Pooja  Verma", "ADITYA ROY", "  Isha Malhotra",
        "dev singh", "Nisha Agarwal "
    ],

    "Email": [
        "RAHUL.SHARMA @GMAIL.COM",
        "priya.mehta@gmail.com ",
        "aman.khan @yahoo.com",
        "neha.kapoor@gmail.com",
        "ARJUN.SINGH@OUTLOOK.COM",
        "simran.kaur @gmail.com",
        "rohit.verma@gmail.com",
        "priyanka.jain@GMAIL.COM ",
        "karan.malhotra@gmail.com",
        "meena.gupta@gmail.com",
        "vikas.yadav @gmail.com",
        "sneha.patel@gmail.com",
        "rajat.gupta@gmail.com",
        "ANJALI.SINGH @YAHOO.COM",
        "mohit.sharma@gmail.com",
        "pooja.verma@gmail.com ",
        "aditya.roy@gmail.com",
        "isha.malhotra@gmail.com",
        "dev.singh @gmail.com",
        "nisha.agarwal@gmail.com"
    ],

    "Phone": [
        "+91-98765-43210",
        "9876543211",
        "(91) 99887 66554",
        "+91 98765 11223",
        "98765-12345",
        "+91-99999-88888",
        "99999 77766",
        "+91 88888 77777",
        "91-9876543210",
        "9876543210",
        "+91 98765 44321",
        "09876543212",
        "+91-98765-11111",
        "98765 22222",
        "+91-98765-33333",
        "98765.44444",
        "+91 98765 55555",
        "98765-66666",
        "+91-98765-77777",
        "98765 88888"
    ],

    "City": [
        "Delhi ", "MUMBAI", "delhi", "Bangalore ",
        "Gurugram", "CHANDIGARH", "Noida", "noida ",
        "Jaipur", "Delhi", "Gurgaon ", "Ahmedabad",
        "delhi ", "Lucknow", "PUNE", "pune",
        "Kolkata", "Kolkata ", "Delhi", "Noida"
    ],

    "Product": [
        " iPhone 15 ", "Samsung Galaxy S24", "OnePlus 12R",
        "MacBook Air M2", "Dell Inspiron 15", "iPad Air",
        "Apple Watch Series 9", "boAt Headphones",
        "Sony WH-1000XM5", "Canon EOS 1500D", "HP Pavilion",
        "Google Pixel 9", "Redmi Note 14", "Kindle Paperwhite",
        "Sony Bravia TV", "JBL Speaker", "Asus Vivobook",
        "Nikon D3500", "Nothing Phone 2", "Lenovo IdeaPad"
    ],

    "Category": [
        "Mobile-Phones", "mobile phones", "Mobile-Phones ",
        "Laptops", "Laptop", "Tablets", "Smart-Watch",
        "Audio", "audio ", "Camera", "LAPTOPS",
        "Mobile Phones", "mobile-phones", "E-Reader",
        "Television", "Audio-Devices", "Laptop", "CAMERA",
        "Mobile Phones", "Laptops "
    ],

    "Price": [
        "₹79,999", "79999 ", "₹42,999/-", "₹1,05,999",
        "54999", "₹59,999/-", "₹39,999", "₹2,499/-",
        "₹29,999", "₹45,000", "₹68,999", "₹74,999/-",
        "₹24,999", "13999", "₹89,999/-", "₹7,499",
        "Rs. 59,990", "₹52,999/-", "₹39,999", "₹51,999"
    ],

    "Purchase_Date": [
        "15-07-2026", "2026/07/16", "16-07-26",
        "17-Jul-2026", "18/07/2026", "19-07-2026",
        "2026-07-20", "20/07/26", "21-07-2026",
        "22-07-2026", "23-07-2026", "24/07/2026",
        "25-07-2026", "26/07/26", "27-Jul-2026",
        "28-07-2026", "29/07/2026", "30-07-26",
        "31-07-2026", "01-08-2026"
    ],

    "Status": [
        " delivered ", "Delivered", "DELIVERED", "Delivered",
        " delivered", "Cancelled ", "Delivered", "delivered",
        "RETURNED", " Delivered ", "pending", "DELIVERED",
        "Delivered", " cancelled", "Delivered", "DELIVERED ",
        "Delivered", "Returned", "delivered", "Pending "
    ],

    "Address": [
        "New Delhi, Delhi - 110001",
        "Mumbai, MH 400001",
        "Delhi, India 110025",
        "Bengaluru, Karnataka-560001",
        "Gurgaon, Haryana 122001",
        "Sector 17, Chandigarh - 160017",
        "Noida, UP-201301",
        "Noida Sector 62, UP 201309",
        "Jaipur, Rajasthan 302001",
        "Delhi - 110044",
        "Gurgaon, Haryana",
        "Ahmedabad, Gujarat 380001",
        "Delhi, 110018",
        "Lucknow, UP 226001",
        "Pune, Maharashtra 411001",
        "Pune - 411014",
        "Kolkata, WB 700001",
        "Kolkata, West Bengal",
        "Delhi NCR - 110059",
        "Noida, Uttar Pradesh 201301"
    ],

    "Feedback": [
        "Very GOOD!!!",
        "good product :)",
        "Excellent!!!",
        "Nice laptop",
        "Average product",
        "Not bad",
        "Amazing!!!",
        "awesome product!!!",
        "Bad experience!!!",
        "Good quality",
        "Waiting for delivery...",
        "Superb!!!",
        "Value for money",
        "Didn't like it :(",
        "Excellent picture quality",
        "Good!!!",
        "Worth buying",
        "Product damaged!!!",
        "Pretty good :)",
        "Please deliver soon!!!"
    ]
}

df = pd.DataFrame(data)

df

,Customer_ID,Name,Email,Phone,City,Product,Category,Price,Purchase_Date,Status,Address,Feedback
0,C001,Rahul Sharma,RAHUL.SHARMA @GMAIL.COM,+91-98765-43210,Delhi,iPhone 15,Mobile-Phones,"₹79,999",15-07-2026,delivered,"New Delhi, Delhi - 110001",Very GOOD!!!
1,C002,priya mehta,priya.mehta@gmail.com,9876543211,MUMBAI,Samsung Galaxy S24,mobile phones,79999,2026/07/16,Delivered,"Mumbai, MH 400001",good product :)
2,C003,AMAN KHAN,aman.khan @yahoo.com,(91) 99887 66554,delhi,OnePlus 12R,Mobile-Phones,"₹42,999/-",16-07-26,DELIVERED,"Delhi, India 110025",Excellent!!!
3,C004,Neha Kapoor,neha.kapoor@gmail.com,+91 98765 11223,Bangalore,MacBook Air M2,Laptops,"₹1,05,999",17-Jul-2026,Delivered,"Bengaluru, Karnataka-560001",Nice laptop
4,C005,arjun singh,ARJUN.SINGH@OUTLOOK.COM,98765-12345,Gurugram,Dell Inspiron 15,Laptop,54999,18/07/2026,delivered,"Gurgaon, Haryana 122001",Average product
5,C006,Simran Kaur,simran.kaur @gmail.com,+91-99999-88888,CHANDIGARH,iPad Air,Tablets,"₹59,999/-",19-07-2026,Cancelled,"Sector 17, Chandigarh - 160017",Not bad
6,C007,rohit.verma,rohit.verma@gmail.com,99999 77766,Noida,Apple Watch Series 9,Smart-Watch,"₹39,999",2026-07-20,Delivered,"Noida, UP-201301",Amazing!!!
7,C008,PRIYANKA JAIN,priyanka.jain@GMAIL.COM,+91 88888 77777,noida,boAt Headphones,Audio,"₹2,499/-",20/07/26,delivered,"Noida Sector 62, UP 201309",awesome product!!!
8,C009,Karan Malhotra,karan.malhotra@gmail.com,91-9876543210,Jaipur,Sony WH-1000XM5,audio,"₹29,999",21-07-2026,RETURNED,"Jaipur, Rajasthan 302001",Bad experience!!!
9,C010,Meena Gupta,meena.gupta@gmail.com,9876543210,Delhi,Canon EOS 1500D,Camera,"₹45,000",22-07-2026,Delivered,Delhi - 110044,Good quality
10,C011,Vikas Yadav,vikas.yadav @gmail.com,+91 98765 44321,Gurgaon,HP Pavilion,LAPTOPS,"₹68,999",23-07-2026,pending,"Gurgaon, Haryana",Waiting for delivery...
11,C012,Sneha Patel,sneha.patel@gmail.com,09876543212,Ahmedabad,Google Pixel 9,Mobile Phones,"₹74,999/-",24/07/2026,DELIVERED,"Ahmedabad, Gujarat 380001",Superb!!!
12,C013,RAJAT GUPTA,rajat.gupta@gmail.com,+91-98765-11111,delhi,Redmi Note 14,mobile-phones,"₹24,999",25-07-2026,Delivered,"Delhi, 110018",Value for money
13,C014,Anjali Singh,ANJALI.SINGH @YAHOO.COM,98765 22222,Lucknow,Kindle Paperwhite,E-Reader,13999,26/07/26,cancelled,"Lucknow, UP 226001",Didn't like it :(
14,C015,mohit sharma,mohit.sharma@gmail.com,+91-98765-33333,PUNE,Sony Bravia TV,Television,"₹89,999/-",27-Jul-2026,Delivered,"Pune, Maharashtra 411001",Excellent picture quality
15,C016,Pooja Verma,pooja.verma@gmail.com,98765.44444,pune,JBL Speaker,Audio-Devices,"₹7,499",28-07-2026,DELIVERED,Pune - 411014,Good!!!
16,C017,ADITYA ROY,aditya.roy@gmail.com,+91 98765 55555,Kolkata,Asus Vivobook,Laptop,"Rs. 59,990",29/07/2026,Delivered,"Kolkata, WB 700001",Worth buying
17,C018,Isha Malhotra,isha.malhotra@gmail.com,98765-66666,Kolkata,Nikon D3500,CAMERA,"₹52,999/-",30-07-26,Returned,"Kolkata, West Bengal",Product damaged!!!
18,C019,dev singh,dev.singh @gmail.com,+91-98765-77777,Delhi,Nothing Phone 2,Mobile Phones,"₹39,999",31-07-2026,delivered,Delhi NCR - 110059,Pretty good :)
19,C020,Nisha Agarwal,nisha.agarwal@gmail.com,98765 88888,Noida,Lenovo IdeaPad,Laptops,"₹51,999",01-08-2026,Pending,"Noida, Uttar Pradesh 201301",Please deliver soon!!!